### ISSUE TITLE
Total Cost

### ISSUE THREAD

**Issue by ijm7** [Team11-AC32006-AC52001/delivrhyno#16]
I have completed the userPay.php page, however could it possibly be expanded to show the total cost of all items ordered. If someone has a method please let me know, if it is already being used for the basket for example.

**Comment by aGrimes94** [comment]
I would assume you would get the .row[menu_item_price] value of each item where &Item1 = restaurant_menu_item_id and then simply add them together. They are being stored as doubles in the database and should be pulled from it as a double type value.
